spring:
  application:
    name: libraryapi
  output:
    ansi:
      enabled: ALWAYS # habilitar cores no console
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: update # atualiza/cria as tabelas direto pela aplicação
      ddl-auto: none # para alterar os campos do banco manualmente, sem ser direto pela aplicação
    properties:
      hibernate.format_sql: true
# gerando automaticamente as tabelas no banco de dados com JPA
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level:
    root: warn
    br:
      com:
        murilo:
          libraryapi: trace # pode fazer uma configuração específica para os níveis de pacote
    org:
      springframework:
        web: debug
        security: trace

# trace
# debug
# info
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

sprindoc:
  override-with-generic-response: false